config/routes.rb
Rails.application.routes.draw do
  root to:'homes#top'
  devise_for :users

  get "homes/master"=>"homes#master" ,as: "master"
  get "homes/user"=>"homes#user", as: "user"
  get "homes/example"=>"homes#example" , as: "example"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user.email=="master@sample"
     master_path
    else
     user_path
    end
  end



  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/example.html.erb
表示分岐用のページです

<%if current_user.email=="master@sample"%>
  <h1>あなたは管理者です</h1>
<%else%>
  <h1>あなたはお客様です</h1>
<%end%>

<p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>

app/views/homes/master.html.erb
<h1>これは管理者のtopページです</h1>

<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

<%= link_to "表示分岐ページへ", example_path%>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

<%=link_to "新規登録", new_user_registration_path %>
<%=link_to "ログイン", new_user_session_path %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

app/views/homes/user.html.erb
<h1>これはお客様のtopページです</h1>

<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

<%= link_to "表示分岐ページへ", example_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>